name: update-repo
on:
  workflow_dispatch:
jobs:
  updateRepo:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkingout
        uses: actions/checkout@v3
      - name: Fetch Official Repo
        run: |
          NDATE=$(date +%Y%m%d)
          cd /mnt/
          sudo wget -r -p -np -nc -k -e robots=off --reject=htm,html,js,css --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.69" https://repo.jellyfin.org/releases/plugin/
      - name: Delete&Upgrade Plugins
        run: |
          cd $GITHUB_WORKSPACE
          sudo rm -rf $GITHUB_WORKSPACE/plugin
          sudo rm $GITHUB_WORKSPACE/manifest-stable-jsd.json
          sudo mv /mnt/repo.jellyfin.org/releases/plugin $GITHUB_WORKSPACE/plugin
      - name: Update Json
        run: |
          sudo sed -i "s_repo.jellyfin.org/releases_cdn.jsdelivr.net/gh/LxnChan/jellyfin-plugin-mirror@${NDATE}_" "$GITHUB_WORKSPACE/plugin/manifest-stable.json"
          sudo sed -i "s_https://github.com_https://gh-proxy.arlxn.top/https://github.com_" "$GITHUB_WORKSPACE/plugin/manifest-stable.json"
          sudo sed -i "s_https://raw.githubusercontent.com_https://gh-proxy.arlxn.top/https://raw.githubusercontent.com_" "$GITHUB_WORKSPACE/plugin/manifest-stable.json"
          sudo cp "$GITHUB_WORKSPACE/plugin/manifest-stable.json" "$GITHUB_WORKSPACE/manifest-stable-jsd.json"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          message: 'autopublish ${date}'
      # Push to Repo
      # Create a Release with name "NDATE"
